spring:
  datasource:
    url: jdbc:postgresql://localhost:8010/postgres
    username: notification
    password: notification
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:29092
    template:
      default-topic: "notification_topic"

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.type.mapping: "event:ru.kashtanov.notification_service.event.OrderEvent"
      group-id: "notificationId"



eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}


