spring:
  datasource:
    url: jdbc:mysql://localhost:5010/mail
    username: mail
    password: mail
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:

      ddl-auto: update
    properties:
      hibernate:

        show_sql: true
        format_sql: true
server:
  port: 8085


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}