version: "3.9"
services:
  pgsql:
    image: postgres:13-alpine
    container_name:  order-service-docker-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    ports:
      - "6010:5432"

  pgadmin:
    image: dpage/pgadmin4:4.18
    container_name:  PgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: order@order.com
      PGADMIN_DEFAULT_PASSWORD: order
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5011:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - pgsql:pgsql-server

volumes:
  pgsql-data:
  pgadmin-data:

