spring:
  datasource:
    url: jdbc:postgresql://localhost:6010/postgres
    username: order
    password: order
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: order-service
server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}