version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql_mail
    restart: always
    environment:
      MYSQL_DATABASE: mail
      MYSQL_USER: mail
      MYSQL_PASSWORD: mail
      MYSQL_ROOT_PASSWORD: mail
    ports:
      - "5010:3306"
    # (this is just an example, not intended to be a production configuration)

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "5033:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mail

